source 'http://rubygems.org'

ruby '2.1.0'

gem 'unicorn'
gem 'sinatra'
gem 'haml'
gem 'redcarpet'
gem 'sinatra-support', require: 'sinatra/support'
gem 'sinatra-assetpack', require: 'sinatra/assetpack'
gem 'coffee-script'
gem 'compass'
gem 'compass-h5bp'
gem 'mustache'
gem 'shotgun'
gem 'dm-core'
gem 'dm-validations'
gem 'rspec'
gem 'dm-rspec'
