source 'http://rubygems.org'

ruby '2.1.0'

gem 'unicorn'
gem 'sinatra'
gem 'haml'
gem 'redcarpet'
gem 'sinatra-support', require: 'sinatra/support'
gem 'sinatra-assetpack', require: 'sinatra/assetpack'
gem 'coffee-script'
gem 'compass'
gem 'compass-h5bp'
# gem 'mustache', '0.99.4'
gem 'mustache-sinatra'
gem 'shotgun'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-validations'
gem 'rspec'
gem 'dm-rspec'
gem 'factory_girl'
gem 'googlebooks'
