source 'http://rubygems.org'

ruby '2.1.0'

gem 'unicorn'
gem 'sinatra'
gem 'haml'
gem 'sinatra-support', require: 'sinatra/support'
gem 'sinatra-assetpack', require: 'sinatra/assetpack'
gem 'mustache-sinatra'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'dm-validations'
gem 'rspec'
gem 'dm-rspec'
gem 'googlebooks'
gem 'thin'
gem 'shotgun'

